project:
  type: website
  output-dir: docs/
  resources:
    - quarto/
    - cesium/js/oceans.0.1.1.js
website:
  title: "Oceans"
  search: false
  navbar:
    left:
      - text: "About"
        file: about.qmd
      - text: "Development"
        file: development.qmd
      - icon: github
        href: https://github.com/marine-ecologist/oceans
        aria-label: GitHub

format:
  html:
    theme: cyborg
    page-layout: full
    max-width: 24000px
    toc: false
execute:
  echo: true
  warning: false
