project:
  type: website
  output-dir: ../docs
  resources:
    - cesium/index.html
    - cesium/css/*.css
    - cesium/js/*.js
    - d3/*.html
    - d3/*.js

website:
  title: "Oceans"
  site-url: https://marine-ecologist.github.io/oceans/
  repo-url: https://github.com/marine-ecologist/oceans
  search: false
  navbar:
    left:
      - text: "About"
        file: about.qmd
      - text: "Development"
        menu:
          - text: "Changelog"
            file: changelog.qmd
          - text: "D3 implementation"
            file: development.qmd
    right:
      - icon: github
        href: https://github.com/marine-ecologist/oceans
        aria-label: GitHub

format:
  html:
    theme: cyborg
    page-layout: full
    max-width: 24000px
    toc: false

execute:
  echo: true
  warning: false
